### ISSUE TITLE
Angular versions compatibility 

### ISSUE THREAD

**Issue by jacwah** [leodido/ng-caret-aware#36]
According to `bower.json`, this project is only compatible with Angular 1.3.x. I have tried to run it on Angular 1.5.6, which has been working thus far. What reasons are there for requiring specifically 1.3? Can I safely use it on a later version?

Cheers

**Comment by leodido** [comment]
Hai @jacwah I have not tried it with angular versions >= 1.3.x.

Can you report me whether it works with such versions?

**Comment by leodido** [comment]
See commit ffbc983aa8077e5b94eceac4b5f5a09ee541c490.

**Comment by jacwah** [comment]
I created this issue a while ago so can't remember exactly, but from what I wrote here I gather that Angular 1.5.6 worked fine.

**Comment by leodido** [comment]
Thanks for the report!
